version: '3.8'


services:

  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: store-users
    volumes:
      - ./mongo:/data/db
    ports:
      - 27019:27017

#   postgres-db:
#     image: postgres:15.3
#     restart: always
#     environment:
#       POSTGRES_USER: products
#       POSTGRES_DB: store-products
#       POSTGRES_PASSWORD: 123456
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
#     ports:
#       - 5432:5432
